platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'
platform :ios, '7.0'
pod 'ECSlidingViewController', '~> 2.0.3'
